- apptools/lru_cache/__init__.py
- apptools/lru_cache/lru_cache.py
- apptools/lru_cache/tests/test_lru_cache.py
This brings a `trait`'d `LRUCache` to python 2.x by adapting the decorator found in `functools.lru_cache` at https://hg.python.org/cpython/file/4d4a9094bdb0/Lib/functools.py
> Backport and traitsify python 3.x's functools.lru_cache

- apptools/lru_cache/lru_cache.py
- apptools/lru_cache/tests/test_lru_cache.py
This PR changes the newly implemented LRUCache to be based on `collections.OrderedDict` rather than the circular linked list ported from python 3. The linked list version had a bug wherein doubly-inserted values weren't properly handled and another involving recently dropped keys. It was sufficiently complicated that debugging was taking longer than reimplementing.
I'm much happier with this result anyway.
> Reimplement LRUCache on top of OrderedDict.

- CHANGES.txt
- apptools/preferences/preferences.py
- apptools/preferences/preferences_helper.py
- apptools/preferences/tests/preferences_helper_test_case.py
The PreferencesHelper don't work properly when getting/storing unicode strings with non-ascii caracters. This PR intends to fix the issue.
> Fixing unicode support for PreferencesHelper

- CHANGES.txt
- apptools/preferences/preferences.py
- apptools/preferences/preferences_helper.py
- apptools/preferences/tests/preferences_helper_test_case.py
PR #41 was changing the behaviour of the Preference class by not converting object to str anymore. This caused a clear problem when getting preferences from a file as the same call to retrieve a preference could either return a specific type or a unicode object as read by ConfigObj in the file.  
This PR changes the behaviour again and gets back to the original design of Preferences which standardizes on str objects. When setting an object in the Preference class it is automatically converted to a unicode object (defaulting to utf-8 encoded strings as input), the unicode object is then properly serialized as utff-8 str by ConfigObj when saving the prefence to a file. When loading the preference in the preference helper, the object is nicely converted back to its target type, with `Str` as …
> Use a full unicode layer in preferences.py

- apptools/persistence/state_pickler.py
- apptools/persistence/tests/test_state_pickler.py
In Python2 environment, `state_pickler.dump(obj, u'file.path')` would raise an Error, but it is not necessary to do further type checking as `open` already handles that for us.
@prabhuramachandran can you take a look please?  This problem arises when trying Save/Load visualization in Mayavi2 in Python2.7 environment.
> Fix state_pickler.dump in py2

- .travis.yml
- travis-ci-requirements.txt
As agreed with @dpinte in pull request #62, we are dropping 2.6 support for apptools.
This will not bring master back to green, but it's a factor.
> Dropping python 2.6 support

- travis-ci-requirements.txt
We're using Traits UI master, but only using PyFace master for Python 3. The PyFace and Traits UI requirements need to be matched on both Python 2 and Python 3.
> Fix mismatched PyFace and Traits UI requirements.

- apptools/persistence/state_pickler.py
Following the suggestion from:
```
/home/larsoner/python/apptools/build/lib/apptools/persistence/state_pickler.py:661: DeprecationWarning: np.loads is deprecated, use pickle.loads instead
result = numpy.loads(junk, encoding='bytes')
```
> FIX: Fix for NumPy deprecation

- docs/source/appscripting/Introduction.rst
- docs/source/scripting/introduction.rst
Addressing spelling-error-in-manpage lintian tag.
> Fixing some spelling in documentation

- apptools/logger/agent/attachments.py
- apptools/logger/agent/tests/test_attachments.py
- apptools/logger/log_point.py
- apptools/logger/plugin/logger_service.py
- apptools/logger/plugin/tests/test_logger_service.py
> Update cStringIO imports

- apptools/persistence/tests/test_file_path.py
The file path tests fail if the tests are run with a cwd under `/tmp`. This PR provides a workaround: forcing the cwd to be a local repository directory while running those tests.
This issue was causing CI failures in #92.
> Temporarily change cwd when running tests

- CHANGES.txt
Changelog entries for the PRs merged after version 4.4.0 of `apptools`.
The release is planned for tomorrow.
>  Update changelog in prep for release

- CHANGES.txt
- setup.py
`twine check` was unhappy because of the missing `long_description_content_type` kwarg to `setuptools.setup`. This PR fixes that issue.
Weirdly enough, even after adding this kwarg, `twine check` is still unhappy because of a bug upstream in `twine`.
> Add long_description_content_type in setup.py

- CHANGES.txt
- setup.py
Set `IS_RELEASED` to `True`. Note that the PR is against the `release/4.5.x` branch.
Note that this branch also contains a commit cherry-picked from master, which contains the fixes from PR #108
> Release version 4.5.0 of apptools

- MANIFEST.in
Specifically, the `image_LICENSE_Nuvola.txt` file was missing from the manifest and so it was missing from the sdist.
fixes #109
> Add missing image license file to manifest

- apptools/persistence/tests/test_state_pickler.py
The `Long` trait is scheduled to be removed in Traits 6.0.0 (though we may have to rethink that: see enthought/traits#643). This PR replaces the sole use of `Long` in this repository with `Int`.
> Replace a use of the deprecated Long trait with Int

- apptools/persistence/file_path.py
Fixes this SyntaxWarning:
/usr/lib/python3/dist-packages/apptools/persistence/file_path.py:70: SyntaxWarni
ng: "is not" with a literal. Did you mean "!="?
if os.sep is not '/':
> Fix SyntaxWarning in file_path.py

- apptools/io/h5/file.py
Fixes #115, by avoiding the use of `_v_groups.itervalues()` and thereby avoiding PyTables/PyTables#784.
No regression test, because there was already a test that was failing under Python 3.8.
We don't have Python 3.8 support in `etstool`: to verify the fix, you'll need to do something like:
- Create a new Python 3.8 venv and activate it.
- Do a `pip install nose numpy pandas tables` to get the necessary dependencies to run the test suite.
- Install `apptools` with `pip install -e .` from the root directory of the repository.
- Run the tests with `nosetests .`
That test run should fail before this fix, and succeed after it.
> Work around broken _v_groups.itervalues() in PyTables

- .travis.yml
- appveyor.yml
The "finish fast" setting is getting in the way of PR failure diagnoses; this PR removes it.
> Don't finish fast for CI jobs

- apptools/io/tests/file_test_case.py
- apptools/logger/ring_buffer.py
- apptools/naming/tests/pyfs_context_test_case.py
- apptools/persistence/versioned_unpickler.py
- apptools/scripting/tests/test_recorder.py
- docs/source/preferences/Preferences.rst
- docs/source/scripting/introduction.rst
- examples/appscripting/example_script_window.py
- examples/naming/simple.py
- examples/permissions/server/test_client.py
- integrationtests/persistence/test_persistence.py
- integrationtests/persistence/update1.py
- integrationtests/persistence/update2.py
- integrationtests/persistence/update3.py
This PR fixes some remaining uses of the Python 2 `print` statement.
For now, the source should remain compatible with both Python 2 and Python 3, but some of these `print`s will have changed behaviour in Python 2, printing a representation of a tuple instead of space-separated elements. The Python 2 support is going to be short-lived enough that this isn't worth fixing.
> Fix uses of print statement

- apptools/help/help_plugin/help_plugin.py
- apptools/persistence/versioned_unpickler.py
The new module was deprecated in Python 2.6, and doesn't exist in Python 3. This PR replaces its uses with the equivalent type calls.
> Fix uses of the "new" module

- .travis.yml
- appveyor.yml
- etstool.py
- install-edm-osx.sh
This PR makes it so that cron jobs install pyface, traitsui, and traits from source by adding a --source click option used in the install function in etstool.py.
It also removes the python 2.7 and 3.5 builds from CI as we will be dropping their support soon.
Additionally, it fixes #152 my moving the OSX CI onto appveyor and off of travis. 
This cron jobs follow what is done in other ets projects (e.g https://github.com/enthought/envisage/blob/8245931f7e3dfcb6513bfb7dc2ae9b10ca6f89a1/etstool.py#L255-L273)
> Add source click option used on cron jobs - only use python 3.6 on CI - move OSX CI to appveyor

- etstool.py
fixes #149 
by simply bumping 3.5 to 3.6 in click options.
> Use Python 3.6 as the default runtime in etstool module

- etstool.py
Bug introduced in PR https://github.com/enthought/apptools/pull/155/. I should have caught the bug because I reviewed the PR 😅
> Default runtime should be 3.6, not 6

- apptools/io/h5/tests/test_dict_node.py
- apptools/io/h5/tests/test_file.py
- apptools/io/h5/tests/test_table_node.py
- apptools/sweet_pickle/tests/test_two_stage_unpickler.py
- etstool.py
Along with the PRs #159 and #158 , this PR fixes #119 .
This PR updates the testsuite such that the entire test suite is discoverable by the unittest test discovery mechanism instead of the nose test discovery mechanism.
The main change is to refactor test functions into test methods on a unittest `TestCase` classes. Additionally, a few missing `__init__.py` modules were added to ensure that the unittest discovery mechanism actually discovers the tests.
Finally, this PR removes `nose` from the dev env and replaces nose with unittest in the `test` click command in the `etstool` helper module.
> Use unittest instead of nose for test discovery

- apptools/io/tests/test_file.py
- apptools/io/tests/test_folder.py
- apptools/naming/tests/test_context.py
- apptools/naming/tests/test_dir_context.py
- apptools/naming/tests/test_pyfs_context.py
- apptools/preferences/tests/example.ini
- apptools/preferences/tests/test_py_config_file.py
- apptools/type_manager/tests/test_type_manager.py
fixes #162 
This PR simply replaces all occurrences of `self.assert_(` with `self.assertTrue(` to avoid deprecation warnings, and also avoids a ResourceWarning for not closing a file by using a `with` statement when opening the file.  
One thing I noticed when making the `assertTrue` fix was that there are tons of places which use 
`assertEqual(____, True)` or `assertEqual(____, None)` or `assertEqual(____, False)`.  Rather than just `assertTrue`, `assertIsNone` or `assertFalse`.  Similarly there are many places were we have `assertTrue(isinstance(____,____))` instead of `assertIsInstance(__, ___)` etc.  These are extremely minor, just something we may want to clean up
> Fix assert deprecation and resource warnings in testsuite

- .travis.yml
- README.rst
- appveyor.yml
As with other ETS projects, the automated code coverage has not proved reliable or useful. This PR removes it, along with the associated badge in the README.
> Remove automated code coverage reporting

- apptools/_testing/__init__.py
- apptools/_testing/optional_dependencies.py
- apptools/io/h5/table_node.py
- apptools/io/h5/tests/test_table_node.py
Currently `apptools.io.h5` requires `pandas` to be a runtime requirement because `DataFrame` is imported and then used ONCE in `H5TableNode.to_dataframe`.
The `to_dataframe` merely instantiates `DataFrame` with the public attribute `ix` and return that DataFrame. It is fair to assume that if one requires this `to_dataframe`, they should already have pandas in their environment. It is a bit overkill to require pandas to be installed, especially if `to_dataframe` is not actually required in user code.
This PR moves the import of `pandas` in the single method that requires it. And fixes the tests for H5TableNode so that they are skipped if NumPy and PyTables are not available.  The latter contributes towards #99 (but it does not close the issue).
> Require pandas on the only method that requires it

- setup.py
#172, #173, #175 will bring about backward incompatible changes: removal of packages.
This PR bumps the version to 5.0.0.dev0, which is equivalent to 4.6.0.dev0 as far as version comparison goes if we will never have a 4.6.0 (I think?). This will do two things (1) signal the master branch is preparing itself for a major release and (2) when we release, we don't accidentally release 4.6.0.
> Bump major version for the next release

- apptools/help/help_plugin/help_plugin.py
This PR simply deletes code that was commented out from `apptools.help.help_plugin.help_plugin.py`.
Robert Martin told me to basically blindly delete any commented out code without trying to understand it.
> Remove commented out code

- .github/pull_request_template.md
- docs/releases/README.rst
- docs/releases/upcoming/116.bugfix.rst
- docs/releases/upcoming/172.removal.rst
- docs/releases/upcoming/173.removal.rst
- docs/releases/upcoming/175.removal.rst
- etstool.py
This PR proposes a small developer workflow to add news fragments for the generation of Changelog.
The idea is that a PR will contribute a small fragment to the changelog, if the changes from the PR is news worthy for the end-users. This will ease the process of having to parse and digest many PRs at the time of making a release. That manual process is particular tedious for PRs that are merged around the time of a previous release but not actually included in that release (this is more of an issue for projects that run a maintenance branch and have many PR activities).
Similar routines can be found in CPython, NumPy, SymPy and various other projects. This is a cheap first-cut solution, without nice tooling like GitHub bots etc.
This PR
- Adds GitHub Pull Request template to remind us of …
> Add routine to add changelog news fragment

- apptools/preferences/tests/py_config_file.py
- apptools/preferences/tests/test_preference_binding.py
- apptools/preferences/tests/test_preferences.py
- apptools/preferences/tests/test_preferences_helper.py
- apptools/preferences/tests/test_py_config_file.py
- apptools/preferences/tests/test_scoped_preferences.py
Bare returns at the end of a function is unnecessary. This PR removes the ones in `apptools.preferences.tests`.
This is a localized effort, so that when we try to add tests in the package, we don't have to be forced to add those returns because that's the consistent thing to do in the local context.
**Checklist**
- Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst): Not news worthy
> Remove bare returns in preferences tests

- docs/releases/upcoming/190.removal.rst
- etstool.py
- setup.py
This PR updates `setup.py` and `etstool.py` to remove support for Python 2.7 and Python 3.5.
The changes on `setup.py` will be useful for package managers downstream that are automatically building open-source packages (I wish Python 2.7 was gone from the world but there exists systems that still requires it.)
Related to #120
**Checklist**
> Explicitly requires Python >= 3.6

- .travis.yml
- appveyor.yml
Fixes #154 
This PR simply bumps the version number for the edm version from 2.0.0 to 3.0.1 in the appveyor and travis yml files.
> Use the latest EDM version (>=3.0.1)

- apptools/selection/tests/test_list_selection.py
- apptools/selection/tests/test_selection_service.py
- apptools/undo/tests/test_command_stack.py
This PR updates `unittest` imports to use the `unittest` standard library package directly instead of importing from `traits` testing utility. This might have been done earlier to provide compatibility between unittest2 on python 2 and unittest on python 3 but now that we are python 3 only, this is not needed.
Note additionally that the traits module has long been updated to only export the `unittest` standard library - https://github.com/enthought/traits/blob/master/traits/testing/unittest_tools.py
contributes towards #120
> Dont import unittest from traits

- apptools/logger/agent/tests/test_attachments.py
- apptools/logger/plugin/tests/test_logger_service.py
- etstool.py
This PR removes the compatibilty layer for `mock` imports for python 2 vs python 3 compatibility, now that the package is moving towards python 3 only. This PR also removes `mock` as a dependency from the `etstool` development utility.
contributes towards #120
> Remove mock compatibility imports on Python 2

- docs/releases/upcoming/198.doc.rst
- docs/source/api.rst
- docs/source/preferences/Preferences.rst
- docs/source/preferences/PreferencesInEnvisage.rst
Closes #42
This PR updates the Preferences section in the documentation.
I re-run the code mentioned in the documentation and updated the output.
I also removed a block which advertises mutating the class attribute (which has a trait type) directly. If it had worked before, it does not work any more. I am tempted to say this is probably not a good pattern anyway to mutate global state on PreferencesHelper so I did not open a new issue.
There are some minor, opportunistic visual updates in the sections/subsections organization.
For example, a couple of sections are at the same level as "Preferences" itself, so previously the TOC looks confusing:
Now those sections are made subsections, so the TOC looks like this:
**Checklist**
> Refresh Preferences documentation

- apptools/logger/agent/quality_agent_mailer.py
- apptools/naming/py_context.py
- apptools/naming/pyfs_context.py
- apptools/persistence/spickle.py
- apptools/persistence/versioned_unpickler.py
- apptools/preferences/ui/i_preferences_page.py
- apptools/preferences/ui/preferences_manager.py
- apptools/preferences/ui/preferences_page.py
- apptools/scripting/tests/test_recorder.py
- integrationtests/persistence/test_persistence.py
Throughout the `apptools` code base there was a lot of commented out code.  Some of it is print statements or no longer used import statements.  Others are things like "we want to be able do this: (bunch of code)  but it doesn't work right now.  These things should be github issues and not clouding the code base.  If a reviewer finds anything deleted here to be important, it can be added back, or preferably have a github issue opened.  Other cases seem like they were part of a PR review process in the form of # actually we dont need this # some code.  These have been removed as well. 
**Checklist**
> remove dead code

- apptools/persistence/state_pickler.py
- apptools/persistence/tests/test_version_registry.py
- apptools/persistence/versioned_unpickler.py
related to #120 
Since #190 has been merged and we intend to drop python 2 I believe it is fine to remove these checks now.  The changes in this PR all occur in the `persistence` sub package which right now, AFAIK, we plan on keeping.
Additionally see here: 
https://github.com/enthought/apptools/blob/a693c79e8547ccaafcf89f230c0b17edbc780655/apptools/persistence/spickle.py#L19-L20
I left this for now as there is already a relevant issue open: #57 
**Checklist**
> Remove all checks for python version < 3 as we are dropping python2

- .travis.yml
- etstool.py
- setup.cfg
This PR sets up flake8 for the codebase. A new `flake8` command is added to `etstool.py` but all of `apptools` is excluded when running `flake8`. The idea is to slowly get the codebase flake8-clean. Note that `examples`, `integrationtests` and `etstool.py`, `setup.py` are also flake8 targets.
contributes towards #145 
**Checklist**
> Setup flake8

- etstool.py
- setup.cfg
Drive-by updates to the flake8 settings.
- `apptools/_testing` is already flake8-clean on master.
- `docs/source/conf.py` should be flaked too? (I can revert that)
- We expect unused imports in `*/api.py` files, skip all of them (so we don't have to laboriously skip F401 at every single line). 
**Checklist**
- ~Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)~ Not news worthy
> Update flake8 ignores

- docs/releases/README.rst
- etstool.py
Motivated by #210, this PR proposes adding a category for news fragments.
Certain changes to test suites may be of interest to distribution packagers (e.g. the build team building EDM eggs, people building packages for Ubuntu, etc.). This PR adds a category for these kind of news fragments to be added and used while building the changelog.
**Checklist**
- ~Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)~ Not news worthy as this is internal changes for developers maintaining apptools.
> Maint: Add test suite to the category of changes in Changelog

- apptools/persistence/tests/test_state_pickler.py
- docs/releases/upcoming/210.test.rst
Closes #209
`base64.decodestring` is deprecated in 3.1, and has been an alias of decodebytes
I searched the code base of apptools and it has only been used in tests. This PR fixes that particular tests.
Since we don't yet run against Python 3.9 on CI, I ran the test suite locally to verify it passes on Python 3.9 and OSX.
**Checklist**
While this may not be news worthy for developers using apptools, this is perhaps news worthy for distribution packagers who run package test suites against their systems (that is, if they also have all the optional dependencies e.g. pytables, but that is an orthogonal issue.)
> Fix Tests' AttributeError in Python 3.9 with base64.decodestring

- apptools/logger/api.py
- apptools/logger/logger.py
- docs/releases/upcoming/218.removal.rst
fixes #214 
This PR simply removes the deprecated `create_log_file_handler` function from `apptools.logger.logger` and removes its import from the api module.  
**Checklist**
> Remove deprecated create_log_file_handler

- apptools/persistence/tests/test_file_path.py
- apptools/preferences/tests/test_preference_binding.py
- apptools/preferences/tests/test_preferences.py
- apptools/preferences/tests/test_preferences_helper.py
- apptools/preferences/tests/test_py_config_file.py
- apptools/preferences/tests/test_scoped_preferences.py
- etstool.py
- setup.py
This PR replaces the use of `pkg_resources.resource_filename` with `importlib_resources.files`. Ref the migration guide for `importlib_resources` - https://importlib-resources.readthedocs.io/en/latest/migration.html#pkg-resources-resource-filename
**Checklist**
> Replace pkg_resources with importlib_resources

- docs/releases/upcoming/221.doc.rst
- docs/source/index.rst
- docs/source/naming/Introduction.rst
Closes #139 (for now at least, we may want to bulk up the documentation at some point)
This PR adds a very small section to the apptools documentation for the `naming` subpackage.  All it says is that this is a python implementation of the Java Naming and Directory Interface, and provides a couple links to JDNI documentation. 
Note the two links are a little redundant (there is repeated information between them), but some things are different.  (I'm not exactly sure why both links exist, and the content isn't merged)
**Checklist**
> Document apptools.naming

- apptools/persistence/tests/test_version_registry.py
This is a simple fix to the deprecation warning seen in #208
Closes #208
**Checklist**
- ~Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)~ Not news worthy
> Fix DeprecationWarning from importing imp

- apptools/io/h5/table_node.py
- apptools/io/h5/tests/test_dict_node.py
- apptools/logger/log_point.py
- apptools/naming/pyfs_context.py
- apptools/naming/trait_defs/naming_traits.py
- apptools/preferences/preference_binding.py
- apptools/preferences/preferences.py
- apptools/preferences/tests/py_config_file.py
- apptools/scripting/recorder.py
- apptools/sweet_pickle/__init__.py
- apptools/sweet_pickle/global_registry.py
- apptools/type_manager/adapter_manager.py
- apptools/type_registry/tests/dummies.py
- apptools/type_registry/type_registry.py
- setup.py
part of #120 
This PR removes all uses of `six` and replaces the occurrences with just the python 3 specific code. 
**Checklist**
Not adding a news fragment as one already exists saying "Remove support for Python 2.7 and 3.5".  That is what is relevant to `apptools` users.
> Remove all use of six 

- apptools/preferences/preferences_helper.py
- apptools/preferences/tests/test_preferences_helper.py
- apptools/preferences/ui/preferences_page.py
- apptools/preferences/ui/tests/test_preferences_page.py
- docs/releases/upcoming/226.bugfix.rst
Closes #225
This PR changes the listener for synchronizing the traits on the PreferencesHelper and PreferencesPage with the preferences, such that if the helper / page has a trait with a name suffix `_items` defined, it would not be mistaken as the event trait for list/set/dict mutation. Otherwise it would assume it is the event trait for list/set/dict mutation, and handle it specifically. If the assumption is wrong, the change handler will raise an error, but the error will be captured in a normal run condition and the default log message will appear.
This fix is possible because one cannot have a trait called `name` and a trait called `name_items` (not an event) and expect both of them to operate normally. Consider the following traits-only tests:
```
import unittest
from traits.api …
```
> Fix use of _items as a normal trait in PreferencesHelper and PreferencesPage

- apptools/preferences/preferences.py
- apptools/preferences/scoped_preferences.py
- apptools/preferences/tests/py_config_file.py
- apptools/preferences/ui/preferences_node.py
Part of #120 
This PR simply removes occurrences of `from __future__ import print_function` across the `apptools` codebase.
**Checklist**
> Remove occurrences of `from __future__ import print_function`

- docs/releases/upcoming/237.doc.rst
- docs/source/index.rst
- docs/source/io/introduction.rst
fixes #53 
This PR adds a _brief_ section to the documentation discussing the `apptools.io` and `apptools.io.h5` sub packages.
**Checklist**
> Add a short documentation section about the io sub-package

- apptools/naming/__init__.py
- apptools/naming/context.py
- apptools/naming/dir_context.py
- apptools/naming/dynamic_context.py
- apptools/naming/object_serializer.py
- apptools/naming/pyfs_context.py
- apptools/naming/reference.py
- apptools/naming/tests/test_context.py
- apptools/naming/tests/test_dir_context.py
- apptools/naming/tests/test_object_serializer.py
- apptools/naming/tests/test_pyfs_context.py
- apptools/naming/trait_defs/__init__.py
- apptools/naming/trait_defs/naming_traits.py
- etstool.py
- setup.cfg
fixes #145 
After this PR, the `setup.cfg` exclude section is entirely empty.  We still have the per-file-ignores for F401 errors in `api` and `__init__` files which should stay.  We also still ignore E266 and W503 errors but I believe that is intended to remain the case.  
**Checklist**
> Final flake8 fixes

- apptools/preferences/tests/test_preferences_helper.py
This PR removes a test that demonstrates the (unexpected) behaviour noted in #194.
The test actually fails with Traits 6.0 because the particular setup of List of List happened to work there:
```
======================================================================
FAIL: test_nested_container_mutation_not_supported (apptools.preferences.tests.test_preferences_helper.PreferencesHelperTestCase)
Known limitation: mutation on nested containers are not
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/kchoi/Work/ETS/apptools/apptools/preferences/tests/test_preferences_helper.py", line 316, in test_nested_container_mutation_not_supported
self.assertEqual(
AssertionError: AssertionError not raised
```
There is no much apptools …
> Remove a redundant test

- apptools/scripting/tests/test_recorder.py
Closes #223
**Checklist**
- ~Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)~ Only concern warnings from tests, not news worthy
> Fix deprecation warning from tests using TraitPrefixMap

- docs/releases/upcoming/247.doc.rst
- docs/source/scripting/introduction.rst
This PR updates documentation to remove usage of `TraitPrefixMap` which has been deprecated since Traits 6.1.
The example is the same as the one #244 modified in tests. Since this is for documentation, I think we can assume latest Traits version and there are no need to rewrite a compatibility layer there.
**Checklist**
> Remove use of TraitPrefixMap in documentation example

- etstool.py
This PR makes a change to the `python etstool.py changelog build` command such that only the found news fragment files are removed.
Motivation: If a news fragment file was misnamed, the build command won't collect its content. If the build command deletes the entire directory, such an omission will be harder to spot. By deleting only the found files, one can verify that the folder containing news fragments is indeed empty after build (with clean).
**Checklist**
- ~Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)~ No change to developer workflow
> Maint: Remove found news fragments rather than indiscriminately deleting all fragments in the folder

- docs/releases/upcoming/248.doc.rst
- docs/source/preferences/PreferencesInEnvisage.rst
- docs/source/scripting/introduction.rst
fixes #171 
Note when writing issue 171 I noticed the broken links on https://docs.enthought.com/apptools/.  I had not built the documentation from master, and after doing so it seems that the majority of the links were working on master.  I went through and checked links from the docs built on master and those that were still broken I have fixed here (only a few).
**Checklist**
> fix a few broken links in documentation

- docs/releases/upcoming/250.deprecation.rst
PR #250 was merged without a news fragment, but it needs one.  This PR simply adds that news fragment.
**Checklist**
> add news fragment for apptools.undo deprecation

- setup.py
This PR simply bumps the version number in setup.py for continued development in advance of the 7.2.0 minor release.
**Checklist**
> Bump version for continued development (5.1.x)

- CHANGES.txt
- docs/releases/upcoming/116.bugfix.rst
- docs/releases/upcoming/172.removal.rst
- docs/releases/upcoming/173.removal.rst
- docs/releases/upcoming/175.removal.rst
- docs/releases/upcoming/184.removal.rst
- docs/releases/upcoming/190.removal.rst
- docs/releases/upcoming/196.bugfix.rst
- docs/releases/upcoming/198.doc.rst
- docs/releases/upcoming/199.removal.rst
- docs/releases/upcoming/210.test.rst
- docs/releases/upcoming/215.removal.rst
- docs/releases/upcoming/216.removal.rst
- docs/releases/upcoming/217.removal.rst
- docs/releases/upcoming/218.removal.rst
- docs/releases/upcoming/219.removal.rst
- docs/releases/upcoming/220.removal.rst
- docs/releases/upcoming/221.doc.rst
- docs/releases/upcoming/226.bugfix.rst
- docs/releases/upcoming/233.removal.rst
- docs/releases/upcoming/237.doc.rst
- docs/releases/upcoming/248.doc.rst
- docs/releases/upcoming/250.deprecation.rst
[Targeting maint/5.0]
This PR simply updates the changelog for the 5.0.0 release (by using the `python etstool.py changelog build` command).  In doing so it deletes all of the news fragments files.  Further in adds a release description in the changelog
**Checklist**
> Update changelog for 5.0.0 release and remove news fragment files

- apptools/io/h5/tests/test_dict_node.py
- apptools/io/h5/tests/test_file.py
- apptools/persistence/tests/test_file_path.py
- apptools/persistence/tests/test_state_pickler.py
- apptools/persistence/tests/test_version_registry.py
- apptools/selection/tests/test_list_selection.py
- docs/releases/upcoming/260.test.rst
fixes #99 
This PR uses the existing `apptools._testing.optional_dependencies` to ensure that optional dependencies are optional for tests.  The test suite should no longer fail if certain optional dependencies are not installed.
**Checklist**
> Make sure optional dependencies are optional for tests

- README.rst
- apptools/logger/log_point.py
- apptools/logger/plugin/logger_service.py
- docs/releases/upcoming/257.build.rst
- setup.py
fixes #176 
This PR adds to the `extras_require` section in `setup.py` to include additional optional dependencies.  It also mentions these in the readme so they are more apparent (Should I add instructions saying to run `pip install apptools[h5]` for examples?  I thought that might be overkill, but was unsure).
Note in this PR when looking for any optional dependencies I saw `io` imports listed as third party imports, so I moved those to be with standard library imports 
**Checklist**
> Add extras_require to setup.py for optional dependencies

- docs/releases/README.rst
- etstool.py
Motivated by #257
This PR adds a new category for the news fragments containing build system related changes. 
**Checklist**
- ~Add a news fragment if this PR is news-worthy for end users. (see docs/releases/README.rst)~
> Add a new category for build system related changes

- setup.py
[targeting maint/5.0]
This PR bumps the release version and flips the IS_RELEASE flag for the development of the next bug fix release.
**Checklist**
> Bump release version for the development of 5.0.1

- CHANGES.txt
This PR simply updates the changelog to match the updates that were made on maint/5.0.
It also adds the release date.
**Checklist**
> Update changelog master after release of 5.0.0

- apptools/undo/action/api.py
This fixes an issue introduced in the PR #272 - `apptools.undo.action.api` tries importing `RedoAction`/`UndoAction` from `pyface.undo.action.command_action` - which is not the right thing to do. This import has been updated to use `pyface.undo.action.api` instead.
This also fixes an new sphinx warning introduced in #272 
**Checklist**
> Correct RedoAction/UndoAction imports from pyface

- setup.py
This PR simply bumps the version number in setup.py for continued development in advance of the 5.1.0 minor release.
**Checklist**
> Bump version for continued development (5.2.x)

- CHANGES.txt
- docs/releases/upcoming/116.bugfix.rst
- docs/releases/upcoming/172.removal.rst
- docs/releases/upcoming/173.removal.rst
- docs/releases/upcoming/175.removal.rst
- docs/releases/upcoming/184.removal.rst
- docs/releases/upcoming/190.removal.rst
- docs/releases/upcoming/196.bugfix.rst
- docs/releases/upcoming/198.doc.rst
- docs/releases/upcoming/199.removal.rst
- docs/releases/upcoming/210.test.rst
- docs/releases/upcoming/215.removal.rst
- docs/releases/upcoming/216.removal.rst
- docs/releases/upcoming/217.removal.rst
- docs/releases/upcoming/218.removal.rst
- docs/releases/upcoming/219.removal.rst
- docs/releases/upcoming/220.removal.rst
- docs/releases/upcoming/221.doc.rst
- docs/releases/upcoming/226.bugfix.rst
- docs/releases/upcoming/233.removal.rst
- docs/releases/upcoming/237.doc.rst
- docs/releases/upcoming/248.doc.rst
- docs/releases/upcoming/250.deprecation.rst
- docs/releases/upcoming/257.build.rst
- docs/releases/upcoming/260.test.rst
- docs/releases/upcoming/272.deprecation.rst
- docs/releases/upcoming/274.doc.rst
[Targeting maint/5.1]
This PR simply updates the changelog for the 5.1.0 release (by using the python etstool.py changelog build command). In doing so it deletes all of the news fragments files. Further in adds a release description in the changelog
**Checklist**
> update changelog for 5.1.0 release and remove news fragment files

- docs/source/undo/Introduction.rst
This PR adds a warning to the Undo section of the documentation about the deprecation and refers to pyface.undo
**Checklist**
This PR does not need a news fragment as the deprecation has already been documented in the changelog.
This PR needs to be backported to maint/5.1
> Mention Undo is deprecated in docs

- docs/source/undo/Introduction.rst
[Targeting maint/5.1]
This PR backports the recent documentation PR (#278) to the maint/5.1 branch in preparation for the upcoming release.
**Checklist**
Changelog does not need to be updated.
> Backports for 5.1.0

- CHANGES.txt
- docs/releases/upcoming/116.bugfix.rst
- docs/releases/upcoming/172.removal.rst
- docs/releases/upcoming/173.removal.rst
- docs/releases/upcoming/175.removal.rst
- docs/releases/upcoming/184.removal.rst
- docs/releases/upcoming/190.removal.rst
- docs/releases/upcoming/196.bugfix.rst
- docs/releases/upcoming/198.doc.rst
- docs/releases/upcoming/199.removal.rst
- docs/releases/upcoming/210.test.rst
- docs/releases/upcoming/215.removal.rst
- docs/releases/upcoming/216.removal.rst
- docs/releases/upcoming/217.removal.rst
- docs/releases/upcoming/218.removal.rst
- docs/releases/upcoming/219.removal.rst
- docs/releases/upcoming/220.removal.rst
- docs/releases/upcoming/221.doc.rst
- docs/releases/upcoming/226.bugfix.rst
- docs/releases/upcoming/233.removal.rst
- docs/releases/upcoming/237.doc.rst
- docs/releases/upcoming/248.doc.rst
- docs/releases/upcoming/250.deprecation.rst
- docs/releases/upcoming/257.build.rst
- docs/releases/upcoming/260.test.rst
- docs/releases/upcoming/272.deprecation.rst
- docs/releases/upcoming/274.doc.rst
This PR simply updates the changelog to match the updates that were made on maint/5.1.
**Checklist**
> Update changelog master after release of 5.1.0

- apptools/persistence/tests/test_file_path.py
- apptools/preferences/tests/test_preference_binding.py
- apptools/preferences/tests/test_preferences.py
- apptools/preferences/tests/test_preferences_helper.py
- apptools/preferences/tests/test_py_config_file.py
- apptools/preferences/tests/test_scoped_preferences.py
- setup.py
Because `importlib_resources` is the backport of `importlib.resources`, the standard lib module should be preferred if it is available.
> python39: importlib_resources -> importlib.resources

- apptools/logger/plugin/logger_service.py
- apptools/logger/plugin/view/logger_view.py
- apptools/preferences/preference_binding.py
- apptools/preferences/tests/test_preference_binding.py
- apptools/preferences/tests/test_preferences_helper.py
- apptools/preferences/ui/widget_editor.py
- apptools/scripting/recorder_with_ui.py
- docs/releases/upcoming/285.feature.rst
**Checklist**
This PR replaces _almost_ all uses of `on_trait_change` with observe.
All that remains is `apptools.selection.selection_service.py` and `apptools.scripting.recorder.py` (also an undo example but that is deprecated here anyway).  These are a bit trickier and can be addressed separately
> Replace on_trait_change with observe

- docs/source/preferences/PreferencesInEnvisage.rst
This PR removes the use of envisage `@contributes_to` decorator in favor of a trait `List` with metadata `contributes_to` instead. This is being done because the next release of envisage removes the decorator entirely. Ref https://github.com/enthought/envisage/pull/402
> Replace use of envisage "contributes_to" decorator in docs

- apptools/logger/plugin/view/logger_view.py
- apptools/naming/tests/test_object_serializer.py
- setup.py
Note these changes now make `apptools` require traits >= 6.2.  ~I checked to specify this requirement, but it appears as though traits isn't even explicitly listed as a requirement, but rather is implicitly required through `traitsui` (which now explicitly requires traits >= 6.2).~ EDIT: I've added `traits>=6.2.0` as an explicit required dependency on this PR.
https://github.com/enthought/apptools/blob/96c3af4213f0d3ab2c831f4e2949a5170d6ff96c/setup.py#L305-L308
**Checklist**
> Replace Property depends_on with observe

- .github/workflows/ets-from-source.yml
- .github/workflows/test-with-edm.yml
Part of #287 (which can be closed when we drop travis and appveyor)
This PR adds two _nearly_ identical work flows.  One of which will run the test suite and flake8 on every PR using packages from edm, the other which will run the test suite as a cron job using ets packages from source. 
**Checklist**
> Port CI to gh-actions

- .github/workflows/ets-from-source.yml
This PR makes it possible to manually trigger the cron job - using `workflow_dispatch`. Ref https://github.com/enthought/ets/issues/68
**Checklist**
> Make it possible to manually trigger cron job

- .github/workflows/ets-from-source.yml
This PR sets up slack notification for the cron job. I manually triggered the cron job on this branch to ensure that the slack notification actually worked as expected. Ref https://github.com/enthought/apptools/actions/runs/1027301837
One more step towards https://github.com/enthought/ets/issues/65.
**Checklist**
> Setup slack notification for cron job

- .readthedocs.yaml
- setup.py
This PR adds a basic configuration file for Read the Docs. These changes are based on enthought/traits#1478. This is one more step towards enthought/ets#69.
This PR also add a `docs` `extras_require` when installing traitsui to make it easy to build the sphinx docs.
**Checklist**
> Add an RtD config file

- .github/ISSUE_TEMPLATE/release_template.md
This PR replaces the use of ``master`` in the repo with ``main`` as the default branch has been renamed.
**Checklist**
>  Default branch has been renamed from "master" to "main"

- apptools/preferences/preference_binding.py
- apptools/preferences/preferences_helper.py
- apptools/preferences/tests/example.ini
- apptools/preferences/tests/test_preference_binding.py
- apptools/preferences/tests/test_preferences_helper.py
- docs/releases/upcoming/299.bugfix.rst
We don't need the full power of `eval()` here, `literal_eval()` should do everything we need, is safer, and anything which breaks can be modified to use a custom trait that is more focused.  This change doesn't break any existing tests, but includes a new test that something which should fail due to the change, does.
**Checklist**
> Replace `eval` with `ast.literal_eval` in apptools.preferences

- apptools/io/h5/file.py
Fixes https://github.com/enthought/apptools/issues/303
Fixed by @susnux
**Checklist**
> fix tests with python 3.10

- .github/workflows/ets-from-source.yml
- .github/workflows/test-with-pip.yml
- pyproject.toml
This PR adds a simple GitHub actions workflow, triggered on pull request (and optionally also manually) that runs the test suite on Python 3.6, 3.8 and 3.10 in a standard Python environment (rather than an EDM environment). The goal is to catch issues like #303 earlier.
---
EDIT: PR updated to also include a `pyproject.toml` file.
> Add workflow that tests against pip packages for various Python versions

- apptools/logger/logger.py
Fix for #323 
Simply adds `encoding` as attribute for `LogFileHandler`.
> FIX: add encoding as an attribute for LogFileHandler initialization

- .github/workflows/ets-from-source.yml
- .github/workflows/publish-on-pypi.yml
- .github/workflows/test-with-edm.yml
- .github/workflows/test-with-pip.yml
- etstool.py
This PR brings our continuous integration workflows back to working state
- Don't try to run non-EDM-based tests on Python 3.6
- Remove uses of GabrielBB/xvfb-action (we don't actually need a virtual framebuffer at all)
- Temporarily pin the copyright end year; we'll fix the copyright headers in a followup PR
- Update EDM and setup-edm-action versions
- Other minor cleanups - e.g., don't update `pip` unnecessarily (the setup-python action already does this for us)
**Checklist**
> Fix GitHub Actions workflows

- .github/workflows/ets-from-source.yml
- .github/workflows/test-with-edm.yml
This PR removes macOS tests for the EDM-based workflows: the EDM builds of NumPy use the AVX2 instruction set, and as 
a result are incompatible with the GitHub Actions runners on macOS.
> Don't run macOS tests with EDM-based workflows

- apptools/persistence/tests/test_state_pickler.py
- docs/releases/upcoming/341.bugfix.rst
This PR removes uses of `numpy.alltrue`, which no longer exists in NumPy 2.0.
**Checklist**
> Remove uses of numpy.alltrue

- apptools/preferences/preferences_helper.py
- apptools/preferences/tests/test_preferences_helper.py
- docs/releases/upcoming/343.bugfix.rst
This PR fixes the `PreferencesHelper` to avoid writing to the preferences the first time a helper is created for a given `Preferences` object.
The issue was that on creation, `PreferencesHelper._initialize` was being called twice: once with `notify=False` and again with `notify=True`, as a result of the listener to the `preferences` trait. This PR avoids the second call by making that listener only run post creation (using `post_init=True`).
Closes #342
Closes #74
**Checklist**
> Avoid writing to preferences on helper creation

- .github/workflows/test-minimal-dependencies.yml
- apptools/_testing/optional_dependencies.py
- apptools/logger/plugin/tests/test_logger_service.py
- apptools/preferences/tests/test_preference_binding.py
- apptools/preferences/tests/test_preferences.py
- apptools/preferences/tests/test_preferences_helper.py
- apptools/preferences/ui/tests/test_preferences_page.py
- docs/releases/upcoming/351.build.rst
- setup.py
Apptools contains several disparate packages with different needs. While it's somewhat reasonable to regard Traits as a core dependency, not all subpackages need a GUI, and only the preferences package makes use of configobj.
This PR:
* makes all three of TraitsUI, Pyface and configobj optional dependencies
* adds a "gui" entry for `extras_require` in `setup.py`
* adds a test workflow that runs the test suite with only the core dependencies (i.e., Traits), to make sure that other tests are skipped appropriately rather than failing
Closes #70 
Makes #86 obsolete.
**Checklist**
> Make TraitsUI, Pyface and configobj optional dependencies

- apptools/persistence/tests/test_state_pickler.py
- docs/releases/upcoming/352.bugfix.rst
Closes #305.
Ideally we'd install Mayavi into the test environment in the test workflows, but I think that's too much of a maintenance risk. It would be even better to find a way to remove the TVTK-specific specializations altogether.
**Checklist**
> Fix equality check in TVTK-related test

- setup.py
This PR removes the `numpy < 2.0` dependency constraint, which should no longer be necessary.
Update: the pin is still needed for Python 3.9 and 3.8; it's been dropped for Python 3.10 and later.
Closes #345.
> Drop a NumPy version pin that should no longer be necessary

- .github/workflows/test-with-pip.yml
> Attempt to run H5 tests on macOS Silicon again
